export const TaskItemState = {
	STARTED: 'STARTED',		// 任务进行中
	SUCCESS: 'SUCCESS',		// 任务执行成功
	FAILURE: 'FAILURE',		// 任务执行失败
	PENDING: 'PENDING',		// 任务不存在
	CANCELED: 'CANCELED',	// 其他标识
};
// 以DAEMON结尾的taskType，界面不展示提示信息，任务台不显示任务进度
export const TaskType = {
	BACKEND: 'BACKEND',
	DELETE_BACKEND: 'DELETE_BACKEND',  // 删除层
	LINK_BACKEND: 'LINK_BACKEND',  // 链接层
	UNLINK_BACKEND: 'UNLINK_BACKEND',  // 取消链接层
	ADD_STATIC:'ADD_STATIC',//添加策略
	EDIT_STATIC:'EDIT_STATIC',//编辑策略
    DELETE_STATIC:'DELETE_STATIC',//删除策略
	ADD_POOLDISK:'ADD_POOLDISK',//添加虚拟磁盘
	DELETE_POOLDISK:'DELETE_POOLDISK',//删除虚拟磁盘
	ASSIGN_DISK_ROLES:'ASSIGN_DISK_ROLES',//配置物理磁盘角色
	RESCAN_PHYSICAL_DISK:'RESCAN_PHYSICAL_DISK',//扫描物理磁盘
	REFRESH_NODE_HARDWARE:'REFRESH_NODE_HARDWARE',//刷新节点硬件功能
	MAKE_NODE_OFFLINE:'MAKE_NODE_OFFLINE',//执行节点offline
    INITIALIZE_ASD:'INITIALIZE_ASD',//初始化磁盘
    STATEMENT_ASD:'STATEMENT_ASD',//声明磁盘
	CLEAR_ASD:'CLEAR_ASD',//移除ASD
	REMOVE_ASD:'REMOVE_ASD',
	DELETE_ASD:'DELETE_ASD',//删除ASD
	ADD_POOL:'ADD_POOL',//添加池
    DELETE_TEMPLATE:'DELETE_TEMPLATE',//删除模板
	DOWNLOAD_ALARM_LOG_DAEMON:'DOWNLOAD_ALARM_LOG_DAEMON',	// 导出告警日志
	CREATE_SNAPSHOT:'CREATE_SNAPSHOT',//创建快照
	ROLLBACK_DISK:'ROLLBACK_DISK',//回滚虚拟磁盘
	SCORUB_DISK:'SCORUB_DISK',//清理虚拟磁盘
	FETCH_STORAGE_ROLES_DAEMON:'FETCH_STORAGE_ROLES_DAEMON',//获取节点角色
	CLONE_DISK:'CLONE_DISK',//克隆虚拟磁盘
	TRANSFER_DISK:'TRANSFER_DISK',//迁移虚拟磁盘
	TRANSFORMAT_DISK:'TRANSFORMAT_DISK',//模板传换
	DELETE_SNAPSHOT:'DELETE_SNAPSHOT',//删除快照
    FETCH_DISK_SAFETY:'FETCH_DISK_SAFETY',//获取磁盘安全性
	REFRESH_VPOOL_CONFIG:'REFRESH_VPOOL_CONFIG',//刷新资源池配置
	GET_CONFIG_PARAMS_DAEMON:'GET_CONFIG_PARAMS_DAEMON',//获取配置数据
	DELETE_VPOOL:'DELETE_VPOOL',//删除资源池
};
//export const BACKEND = 'BACKEND'